# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui/detect_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import ui_img.detect_rc

class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setWindowTitle("基于YOLOv5l的疏果前期幼果识别检测演示软件V1.0")
        self.resize(1600, 900)

        self.centralwidget = QWidget()
        self.centralwidget.setObjectName("centralwidget")

        # 背景图像
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(-11, -10, 1661, 931))
        self.listView.setStyleSheet("background-image: url(:/detect/detect.JPG);")
        self.listView.setObjectName("listView")

        # 模型选择
        self.btn_selet_model = QtWidgets.QPushButton(self.centralwidget)
        self.btn_selet_model.setGeometry(QtCore.QRect(150, 810, 112, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(12)
        self.btn_selet_model.setFont(font)
        self.btn_selet_model.setObjectName("btn_selet_model")

        # 呈现原始图像
        self.label_show_yuanshi = QtWidgets.QLabel(self.centralwidget)
        self.label_show_yuanshi.setGeometry(QtCore.QRect(70, 80, 700, 700))
        self.label_show_yuanshi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_show_yuanshi.setObjectName("label_show_yuanshi")

        # 模型初始化
        self.btn_init_model = QtWidgets.QPushButton(self.centralwidget)
        self.btn_init_model.setGeometry(QtCore.QRect(300, 810, 112, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(12)
        self.btn_init_model.setFont(font)
        self.btn_init_model.setObjectName("btn_init_model")

        # 选择图像进行检测
        self.btn_detect_img = QtWidgets.QPushButton(self.centralwidget)
        self.btn_detect_img.setGeometry(QtCore.QRect(450, 810, 112, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(12)
        self.btn_detect_img.setFont(font)
        self.btn_detect_img.setObjectName("btn_detect_img")

        # 保存结果图像
        self.btn_save_img = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_img.setGeometry(QtCore.QRect(950, 810, 112, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(12)
        self.btn_save_img.setFont(font)
        self.btn_save_img.setObjectName("btn_save_img")

        # 清除结果图像
        self.btn_clear_img = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear_img.setGeometry(QtCore.QRect(1100, 810, 112, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(12)
        self.btn_clear_img.setFont(font)
        self.btn_clear_img.setObjectName("btn_clear_img")

        # 退出应用
        self.btn_exit_app = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit_app.setGeometry(QtCore.QRect(1250, 810, 112, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(12)
        self.btn_exit_app.setFont(font)
        self.btn_exit_app.setObjectName("btn_exit_app")

        # 呈现结果图像
        self.label_show_jieguo = QtWidgets.QLabel(self.centralwidget)
        self.label_show_jieguo.setGeometry(QtCore.QRect(840, 80, 700, 700))
        self.label_show_jieguo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_show_jieguo.setObjectName("label_show_jieguo")

        # 标题
        self.label_show_title = QtWidgets.QLabel(self.centralwidget)
        self.label_show_title.setGeometry(QtCore.QRect(430, 20, 731, 41))
        self.label_show_title.setObjectName("label_show_title")

        # 主窗口
        self.setCentralWidget(self.centralwidget)
        self.retranslateUi(self.centralwidget)
        QtCore.QMetaObject.connectSlotsByName(self.centralwidget)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_selet_model.setText(_translate("MainWindow", "最优模型选择"))
        self.label_show_yuanshi.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">原始图像</span></p></body></html>"))
        self.btn_init_model.setText(_translate("MainWindow", "模型初始化"))
        self.btn_detect_img.setText(_translate("MainWindow", "选择检测图像"))
        self.btn_save_img.setText(_translate("MainWindow", "保存结果图像"))
        self.btn_clear_img.setText(_translate("MainWindow", "清除结果图像"))
        self.btn_exit_app.setText(_translate("MainWindow", "退出应用"))
        self.label_show_jieguo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">结果图像</span></p></body></html>"))
        self.label_show_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; color:#ffffff;\">基于YOLOv5l的疏果前期幼果识别检测演示软件</span></p></body></html>"))

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ui = Ui_MainWindow()
    ui.show()
    sys.exit(app.exec_())