# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'ui/ui/login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
import ui_img.login_rc
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(817, 600)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")

        self.edit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_username.setGeometry(QtCore.QRect(212, 184, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(22)
        self.edit_username.setFont(font)
        self.edit_username.setText("")
        self.edit_username.setObjectName("edit_username")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 100, 811, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.edit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_password.setGeometry(QtCore.QRect(210, 270, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(22)
        self.edit_password.setFont(font)
        self.edit_password.setObjectName("edit_password")

        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(180, 390, 112, 91))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(18)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")

        self.btn_regeist = QtWidgets.QPushButton(self.centralwidget)
        self.btn_regeist.setGeometry(QtCore.QRect(480, 390, 112, 91))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(18)
        self.btn_regeist.setFont(font)
        self.btn_regeist.setObjectName("btn_regeist")

        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, -60, 821, 601))
        self.listView.setStyleSheet("background-image: url(:/loginb/login.JPG);")
        self.listView.setObjectName("listView")
        self.listView.raise_()

        self.edit_username.raise_()

        self.label.raise_()

        self.edit_password.raise_()

        self.btn_login.raise_()

        self.btn_regeist.raise_()

        Form.setCentralWidget(self.centralwidget)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "基于YOLOv5的识别检测演示软件V1.0"))
        self.edit_username.setPlaceholderText(_translate("Form", "用户名"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">基于YOLOv5的识别检测演示软件</span></p></body></html>"))
        self.edit_password.setPlaceholderText(_translate("Form", "密码"))
        self.btn_login.setText(_translate("Form", "登录"))
        self.btn_regeist.setText(_translate("Form", "注册"))

