# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'ui/ui/registe_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
import ui_img.registe_rc
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(805, 600)
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.listView.setStyleSheet("background-image: url(:/registe/registe.JPG);")
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 90, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.edit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_username.setGeometry(QtCore.QRect(250, 190, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(28)
        self.edit_username.setFont(font)
        self.edit_username.setObjectName("edit_username")
        self.pushButton_regiser = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_regiser.setGeometry(QtCore.QRect(200, 400, 112, 81))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(28)
        self.pushButton_regiser.setFont(font)
        self.pushButton_regiser.setObjectName("pushButton_regiser")
        self.edit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_password.setGeometry(QtCore.QRect(250, 300, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(26)
        self.edit_password.setFont(font)
        self.edit_password.setMouseTracking(True)
        self.edit_password.setObjectName("edit_password")
        self.pushButton_cancer = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancer.setGeometry(QtCore.QRect(500, 410, 112, 81))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(28)
        self.pushButton_cancer.setFont(font)
        self.pushButton_cancer.setObjectName("pushButton_cancer")
        Dialog.setCentralWidget(self.centralwidget)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "基于YOLOv5的识别检测演示软件V1.0"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">注册界面</span></p></body></html>"))
        self.edit_username.setPlaceholderText(_translate("Dialog", "注册账号"))
        self.pushButton_regiser.setText(_translate("Dialog", "注册"))
        self.edit_password.setPlaceholderText(_translate("Dialog", "设置密码"))
        self.pushButton_cancer.setText(_translate("Dialog", "取消"))

